// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: src/grpcpb/utcp.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_src_grpcpb_utcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpcpb_utcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_src_grpcpb_utcp_proto_rawDescGZIP(), []int{0}
}

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_src_grpcpb_utcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpcpb_utcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_src_grpcpb_utcp_proto_rawDescGZIP(), []int{1}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Manual struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Tools         []*Tool                `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manual) Reset() {
	*x = Manual{}
	mi := &file_src_grpcpb_utcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manual) ProtoMessage() {}

func (x *Manual) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpcpb_utcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manual.ProtoReflect.Descriptor instead.
func (*Manual) Descriptor() ([]byte, []int) {
	return file_src_grpcpb_utcp_proto_rawDescGZIP(), []int{2}
}

func (x *Manual) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manual) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	ArgsJson      string                 `protobuf:"bytes,2,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallRequest) Reset() {
	*x = ToolCallRequest{}
	mi := &file_src_grpcpb_utcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallRequest) ProtoMessage() {}

func (x *ToolCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpcpb_utcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallRequest.ProtoReflect.Descriptor instead.
func (*ToolCallRequest) Descriptor() ([]byte, []int) {
	return file_src_grpcpb_utcp_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCallRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolCallRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

type ToolCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallResponse) Reset() {
	*x = ToolCallResponse{}
	mi := &file_src_grpcpb_utcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallResponse) ProtoMessage() {}

func (x *ToolCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpcpb_utcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallResponse.ProtoReflect.Descriptor instead.
func (*ToolCallResponse) Descriptor() ([]byte, []int) {
	return file_src_grpcpb_utcp_proto_rawDescGZIP(), []int{4}
}

func (x *ToolCallResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

var File_src_grpcpb_utcp_proto protoreflect.FileDescriptor

const file_src_grpcpb_utcp_proto_rawDesc = "" +
	"\n" +
	"\x15src/grpcpb/utcp.proto\x12\x06grpcpb\"\a\n" +
	"\x05Empty\"<\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"F\n" +
	"\x06Manual\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\"\n" +
	"\x05tools\x18\x02 \x03(\v2\f.grpcpb.ToolR\x05tools\"B\n" +
	"\x0fToolCallRequest\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x1b\n" +
	"\targs_json\x18\x02 \x01(\tR\bargsJson\"3\n" +
	"\x10ToolCallResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson2\xbf\x01\n" +
	"\vUTCPService\x12*\n" +
	"\tGetManual\x12\r.grpcpb.Empty\x1a\x0e.grpcpb.Manual\x12=\n" +
	"\bCallTool\x12\x17.grpcpb.ToolCallRequest\x1a\x18.grpcpb.ToolCallResponse\x12E\n" +
	"\x0eCallToolStream\x12\x17.grpcpb.ToolCallRequest\x1a\x18.grpcpb.ToolCallResponse0\x01B@Z>github.com/universal-tool-calling-protocol/go-utcp//src/grpcpbb\x06proto3"

var (
	file_src_grpcpb_utcp_proto_rawDescOnce sync.Once
	file_src_grpcpb_utcp_proto_rawDescData []byte
)

func file_src_grpcpb_utcp_proto_rawDescGZIP() []byte {
	file_src_grpcpb_utcp_proto_rawDescOnce.Do(func() {
		file_src_grpcpb_utcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_grpcpb_utcp_proto_rawDesc), len(file_src_grpcpb_utcp_proto_rawDesc)))
	})
	return file_src_grpcpb_utcp_proto_rawDescData
}

var file_src_grpcpb_utcp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_grpcpb_utcp_proto_goTypes = []any{
	(*Empty)(nil),            // 0: grpcpb.Empty
	(*Tool)(nil),             // 1: grpcpb.Tool
	(*Manual)(nil),           // 2: grpcpb.Manual
	(*ToolCallRequest)(nil),  // 3: grpcpb.ToolCallRequest
	(*ToolCallResponse)(nil), // 4: grpcpb.ToolCallResponse
}
var file_src_grpcpb_utcp_proto_depIdxs = []int32{
	1, // 0: grpcpb.Manual.tools:type_name -> grpcpb.Tool
	0, // 1: grpcpb.UTCPService.GetManual:input_type -> grpcpb.Empty
	3, // 2: grpcpb.UTCPService.CallTool:input_type -> grpcpb.ToolCallRequest
	3, // 3: grpcpb.UTCPService.CallToolStream:input_type -> grpcpb.ToolCallRequest
	2, // 4: grpcpb.UTCPService.GetManual:output_type -> grpcpb.Manual
	4, // 5: grpcpb.UTCPService.CallTool:output_type -> grpcpb.ToolCallResponse
	4, // 6: grpcpb.UTCPService.CallToolStream:output_type -> grpcpb.ToolCallResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_grpcpb_utcp_proto_init() }
func file_src_grpcpb_utcp_proto_init() {
	if File_src_grpcpb_utcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_grpcpb_utcp_proto_rawDesc), len(file_src_grpcpb_utcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_grpcpb_utcp_proto_goTypes,
		DependencyIndexes: file_src_grpcpb_utcp_proto_depIdxs,
		MessageInfos:      file_src_grpcpb_utcp_proto_msgTypes,
	}.Build()
	File_src_grpcpb_utcp_proto = out.File
	file_src_grpcpb_utcp_proto_goTypes = nil
	file_src_grpcpb_utcp_proto_depIdxs = nil
}
