// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: grpcpb/utcp.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcpb_utcp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpcpb_utcp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpcpb_utcp_proto_rawDescGZIP(), []int{0}
}

type Tool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Tool) Reset() {
	*x = Tool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcpb_utcp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_grpcpb_utcp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_grpcpb_utcp_proto_rawDescGZIP(), []int{1}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Manual struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string  `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Tools   []*Tool `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
}

func (x *Manual) Reset() {
	*x = Manual{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcpb_utcp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Manual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manual) ProtoMessage() {}

func (x *Manual) ProtoReflect() protoreflect.Message {
	mi := &file_grpcpb_utcp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manual.ProtoReflect.Descriptor instead.
func (*Manual) Descriptor() ([]byte, []int) {
	return file_grpcpb_utcp_proto_rawDescGZIP(), []int{2}
}

func (x *Manual) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manual) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tool     string `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	ArgsJson string `protobuf:"bytes,2,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
}

func (x *ToolCallRequest) Reset() {
	*x = ToolCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcpb_utcp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToolCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallRequest) ProtoMessage() {}

func (x *ToolCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcpb_utcp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallRequest.ProtoReflect.Descriptor instead.
func (*ToolCallRequest) Descriptor() ([]byte, []int) {
	return file_grpcpb_utcp_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCallRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolCallRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

type ToolCallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultJson string `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
}

func (x *ToolCallResponse) Reset() {
	*x = ToolCallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcpb_utcp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToolCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallResponse) ProtoMessage() {}

func (x *ToolCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcpb_utcp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallResponse.ProtoReflect.Descriptor instead.
func (*ToolCallResponse) Descriptor() ([]byte, []int) {
	return file_grpcpb_utcp_proto_rawDescGZIP(), []int{4}
}

func (x *ToolCallResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

var File_grpcpb_utcp_proto protoreflect.FileDescriptor

var file_grpcpb_utcp_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2f, 0x75, 0x74, 0x63, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x3c, 0x0a, 0x04, 0x54, 0x6f, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x06, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x05, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x54,
	0x6f, 0x6f, 0x6c, 0x52, 0x05, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x22, 0x42, 0x0a, 0x0f, 0x54, 0x6f,
	0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x6f,
	0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x67, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x33,
	0x0a, 0x10, 0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x6a, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4a,
	0x73, 0x6f, 0x6e, 0x32, 0x78, 0x0a, 0x0b, 0x55, 0x54, 0x43, 0x50, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x12,
	0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x12, 0x3d,
	0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x54, 0x6f, 0x6f, 0x6c, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x6f,
	0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a,
	0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x61, 0x65, 0x7a,
	0x69, 0x6c, 0x2f, 0x55, 0x54, 0x43, 0x50, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcpb_utcp_proto_rawDescOnce sync.Once
	file_grpcpb_utcp_proto_rawDescData = file_grpcpb_utcp_proto_rawDesc
)

func file_grpcpb_utcp_proto_rawDescGZIP() []byte {
	file_grpcpb_utcp_proto_rawDescOnce.Do(func() {
		file_grpcpb_utcp_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcpb_utcp_proto_rawDescData)
	})
	return file_grpcpb_utcp_proto_rawDescData
}

var file_grpcpb_utcp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpcpb_utcp_proto_goTypes = []interface{}{
	(*Empty)(nil),            // 0: grpcpb.Empty
	(*Tool)(nil),             // 1: grpcpb.Tool
	(*Manual)(nil),           // 2: grpcpb.Manual
	(*ToolCallRequest)(nil),  // 3: grpcpb.ToolCallRequest
	(*ToolCallResponse)(nil), // 4: grpcpb.ToolCallResponse
}
var file_grpcpb_utcp_proto_depIdxs = []int32{
	1, // 0: grpcpb.Manual.tools:type_name -> grpcpb.Tool
	0, // 1: grpcpb.UTCPService.GetManual:input_type -> grpcpb.Empty
	3, // 2: grpcpb.UTCPService.CallTool:input_type -> grpcpb.ToolCallRequest
	2, // 3: grpcpb.UTCPService.GetManual:output_type -> grpcpb.Manual
	4, // 4: grpcpb.UTCPService.CallTool:output_type -> grpcpb.ToolCallResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpcpb_utcp_proto_init() }
func file_grpcpb_utcp_proto_init() {
	if File_grpcpb_utcp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcpb_utcp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcpb_utcp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcpb_utcp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Manual); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcpb_utcp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToolCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcpb_utcp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToolCallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcpb_utcp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcpb_utcp_proto_goTypes,
		DependencyIndexes: file_grpcpb_utcp_proto_depIdxs,
		MessageInfos:      file_grpcpb_utcp_proto_msgTypes,
	}.Build()
	File_grpcpb_utcp_proto = out.File
	file_grpcpb_utcp_proto_rawDesc = nil
	file_grpcpb_utcp_proto_goTypes = nil
	file_grpcpb_utcp_proto_depIdxs = nil
}
